### ISSUE TITLE
Spy behaves badly when interacting with promise-like return values

### ISSUE THREAD

**Issue by simon-abbott** [tinylibs/tinyspy#23]
I'm trying to port [mockingoose](https://github.com/alonronin/mockingoose) over to Vitest (which uses tinyspy), and I have run into two issues, both of which are directly due to the way tinyspy handles promise-like return values:

---

Firstly, this code:

```js
mongoose.createConnection = vitest.fn().mockReturnValue({
  catch() {
    /* no op */
  },
  model: mongoose.model.bind(mongoose),
  on: vitest.fn(),
  once: vitest.fn(),
  then(resolve) {
    return Promise.resolve(resolve(this));
  },
});
```

When `mongoose.createConnection()` is called it will hang forever. This is because of this line:

https://github.com/tinylibs/tinyspy/blob/eed04c97a3fec2b026071a1a4becc0af4d5d0ff8/src/spy.ts#L71

which means that `return Promise.resolve(resolve(this))` effectively becomes `await this`, which is an infinite await loop.

---

Secondly, mongoose Query objects are _not promises_, but they do have a `then` function. This function commits the query and awaits the result from the database. The issue is that by calling `then`, again in the same place:

https://github.com/tinylibs/tinyspy/blob/eed04c97a3fec2b026071a1a4becc0af4d5d0ff8/src/spy.ts#L71

tinyspy is inadvertently committing the query well before it should actually be executed, which results in bad behavior. Specifically, this code:

```js
SomeModel.findOne({ id: someId }).populate('someField').exec();
```

fails with the error ".populate() isn't a function", because by the time `fineOne` is finished executing it has already committed the query, even though it shouldn't commit until the call to `exec()`.

---

Here's [a code sandbox](https://codesandbox.io/s/pedantic-pascal-1n5i5l?file=/src/index.ts) with an example of this issue that only uses tinyspy.

I'm not sure what the best solution to this issue is. If the promise resolution code is removed it will fix these issues I've been having, but it was clearly added for a reason. But if it is left in as-is then this code breaks. I'm not a huge fan of adding options or config flags to this library, but I'm struggling to find another option for this issue.

**Comment by Aslemammad** [comment]
@sheremet-va How about checking Promises with this 
```ts
if (value instanceof Promise)
```

**Comment by Aslemammad** [comment]
@simon-abbott I feel #24 should fix this.
