### ISSUE TITLE
Question about changelogithub dep

### ISSUE THREAD

**Issue by vladimirtemnikov** [tinylibs/tinyspy#25]
Hello!
Such a great project!

I have a question. Is `changelogithub` dep supposed to be a direct dependency for this lib?
Actual release had bloated my project deps a bit 😄 

Thank you!

**Comment by sheremet-va** [comment]
No, it shouldn't be 🤔

**Comment by sheremet-va** [comment]
Hopefully, fixed in https://github.com/tinylibs/tinyspy/releases/tag/v1.0.2

**Comment by vladimirtemnikov** [comment]
Thank you, I'll close the issue
