### ISSUE TITLE
1.1.0 breaks instanceOf tests

### ISSUE THREAD

**Issue by Jason3S** [tinylibs/tinyspy#32]
I'm not sure if this was intended, but #31, breaks `instanceof` class.

```ts
import { afterEach, describe, expect, test, vi } from 'vitest';

import { MyClass } from './MyClass';

vi.mock('./MyClass');

const mockedMyClass = vi.mocked(MyClass);

describe('MyClass', () => {
    afterEach(() => {
        mockedMyClass.mockClear();
    });

    test.each`
        name          | expected
        ${'Atlantic'} | ${'Atlantic'}
        ${'Pacific'}  | ${'Pacific'}
    `('new MyClass $name', ({ name, expected }) => {
        const instance = new MyClass(name);
        expect(instance).toBeInstanceOf(MyClass);  // Was working in 1.0.2
        expect(mockedMyClass).toHaveBeenCalledTimes(1);
        expect(mockedMyClass).toHaveBeenCalledWith(expected);
    });
});
```

It is a bit of a contrived example. But I'm not sure how to preserve the inheritance chain.

Repo: https://github.com/Jason3S/tinyspy-issue-32
StackBlitz: https://stackblitz.com/edit/vitest-dev-vitest-dhhorq?file=README.md

**Comment by sheremet-va** [comment]
Doesn't seem to be intentional, @trivikr what do you think?

**Comment by trivikr** [comment]
The error in this case was:
```console
AssertionError: expected <Anonymous Class>{} to be an instance of MyClass
```

I played around with `Function.prototype.bind`, but the error persists
https://stackoverflow.com/a/8843181

**Comment by trivikr** [comment]
The following solution fixes instance of checks:

```ts
        result = new.target
          ? new (fn.impl as any)(...args)
          : fn.impl.apply(this, args)
        if (new.target) Object.setPrototypeOf(r, this);
```

@sheremet-va Would you like to attempt trying it out?

**Comment by sheremet-va** [comment]
> Would you like to attempt trying it out?

What are the performance implications of this?

**Comment by trivikr** [comment]
I think we should follow [Make it work, Make it right, Make it fast](https://thetombomb.com/posts/make-it-work-right-fast).

In this case, the Make it work/right is not true as per https://github.com/tinylibs/tinyspy/issues/29

**Comment by sheremet-va** [comment]
> In this case, the Make it work/right is not true as per https://github.com/tinylibs/tinyspy/issues/29

Only if it is really a bug. These revelations are leading me to believe that this is intended behavior. It is consistent with sinon and jest behaviors at least:

```js
import { stub } from "sinon";
import { ModuleMocker } from "jest-mock";

const obj = {
  className: class Foo {},
};

stub(obj, "className").callsFake(function () {
  console.log(new.target);
});

obj.className(); // undefined
new obj.className(); // undefined

const mocker = new ModuleMocker(global);

mocker.spyOn(obj, "className").mockImplementation(function () {
  console.log(new.target);
});

obj.className(); // undefined
new obj.className(); // undefined
```

**Comment by Jason3S** [comment]
@sheremet-va and @trivikr,

Thank you for the quick response and turn around.

**Comment by trivikr** [comment]
Added a summary in https://github.com/tinylibs/tinyspy/issues/29#issuecomment-1421343259 for future discussion about new.target
